### ISSUE TITLE
Could not find process error

### ISSUE THREAD

**Issue by nnnorbi** [Business99/ScuttleBuddy-External#23]
Loaded: Core.py
Loaded: SpellTracking.py
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\main.py", line 36, in <module>
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pymem\__init__.py", line 44, in __init__
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pymem\__init__.py", line 202, in open_process_from_name
pymem.exception.ProcessNotFound: Could not find process: League of Legends.exe

**Comment by nnnorbi** [comment]
I don't know what causes the problem but im using Win 11 OS build: 25206.1000

**Comment by Business99** [comment]
Hey, do you have a game open? Such as practice tool or a custom lobby

**Comment by nnnorbi** [comment]
I didn't use any tool/tools, and yes i did have the game open.

**Comment by nnnorbi** [comment]
update: after reintsalling python 3.10 it worked so sorry for wasting your time and thanks.
